language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chamow01/practicasReact -f Dockerfile.dev .

script:
  - docker run -e CI=true chamow01/practicasReact npm run test
  
