language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t chamow01/practicas-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chamow01/practicas-react npm run test
  
